name = "edge-api"
main = "dist/worker.js"
compatibility_date = "2026-07-05"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "edge-api"

[[kv_namespaces]]
binding = "KV"
title = "edge-api-kv"

[vars]
SYSTEM_NAME = "Edge API"
