/** Original `config.GlobalConfig.ExportAllConfigs()` nested option keys. */

export const CHANNEL_AFFINITY_RULES = [
  {
    name: "codex cli trace",
    model_regex: ["^gpt-.*$"],
    path_regex: ["/v1/responses"],
    key_sources: [{ type: "gjson", path: "prompt_cache_key" }],
    value_regex: "",
    ttl_seconds: 0,
    param_override_template: {
      operations: [
        {
          mode: "pass_headers",
          value: [
            "Originator",
            "Session_id",
            "Thread_id",
            "Session-Id",
            "Thread-Id",
            "X-Client-Request-Id",
            "User-Agent",
            "X-Codex-Beta-Features",
            "X-Codex-Turn-State",
            "X-Codex-Turn-Metadata",
            "X-Codex-Window-Id",
            "X-Codex-Parent-Thread-Id",
            "X-OpenAI-Subagent",
            "X-OpenAI-Memgen-Request",
            "X-ResponsesAPI-Include-Timing-Metrics",
            "X-OpenAI-Internal-Codex-Responses-Lite",
          ],
          keep_origin: true,
        },
      ],
    },
    skip_retry_on_failure: true,
    include_using_group: true,
    include_model_name: false,
    include_rule_name: true,
  },
  {
    name: "claude cli trace",
    model_regex: ["^claude-.*$"],
    path_regex: ["/v1/messages"],
    key_sources: [{ type: "gjson", path: "metadata.user_id" }],
    value_regex: "",
    ttl_seconds: 0,
    param_override_template: {
      operations: [
        {
          mode: "pass_headers",
          value: [
            "X-Stainless-Arch",
            "X-Stainless-Lang",
            "X-Stainless-Os",
            "X-Stainless-Package-Version",
            "X-Stainless-Retry-Count",
            "X-Stainless-Runtime",
            "X-Stainless-Runtime-Version",
            "X-Stainless-Timeout",
            "User-Agent",
            "X-App",
            "Anthropic-Beta",
            "Anthropic-Dangerous-Direct-Browser-Access",
            "Anthropic-Version",
          ],
          keep_origin: true,
        },
      ],
    },
    skip_retry_on_failure: true,
    include_using_group: true,
    include_model_name: false,
    include_rule_name: true,
  },
];

export const NESTED_OPTION_DEFAULTS: Record<string, string> = {
  "console_setting.api_info": "",
  "console_setting.uptime_kuma_groups": "",
  "console_setting.announcements": "",
  "console_setting.faq": "",
  "console_setting.api_info_enabled": "true",
  "console_setting.uptime_kuma_enabled": "true",
  "console_setting.announcements_enabled": "true",
  "console_setting.faq_enabled": "true",
  "passkey.enabled": "false",
  "passkey.rp_display_name": "",
  "passkey.rp_id": "",
  "passkey.origins": "",
  "passkey.allow_insecure_origin": "false",
  "passkey.user_verification": "preferred",
  "passkey.attachment_preference": "",
  "oidc.enabled": "false",
  "oidc.display_name": "",
  "oidc.client_id": "",
  "oidc.client_secret": "",
  "oidc.well_known": "",
  "oidc.authorization_endpoint": "",
  "oidc.token_endpoint": "",
  "oidc.user_info_endpoint": "",
  "legal.user_agreement": "",
  "legal.privacy_policy": "",
  "discord.enabled": "false",
  "discord.client_id": "",
  "discord.client_secret": "",
  "telegram.client_id": "",
  "telegram.client_secret": "",
  "checkin_setting.enabled": "false",
  "checkin_setting.min_quota": "1000",
  "checkin_setting.max_quota": "10000",
  "general_setting.docs_link": "https://docs.newapi.pro",
  "general_setting.ping_interval_enabled": "false",
  "general_setting.ping_interval_seconds": "60",
  "general_setting.quota_display_type": "USD",
  "general_setting.custom_currency_symbol": "¤",
  "general_setting.custom_currency_exchange_rate": "1",
  "quota_setting.enable_free_model_pre_consume": "true",
  "token_setting.max_user_tokens": "1000",
  "monitor_setting.auto_test_channel_enabled": "false",
  "monitor_setting.auto_test_channel_minutes": "10",
  "monitor_setting.channel_test_mode": "scheduled_all",
  "monitor_setting.channel_test_concurrency": "1",
  "payment_setting.amount_options": JSON.stringify([10, 20, 50, 100, 200, 500]),
  "payment_setting.amount_discount": "{}",
  "payment_setting.compliance_confirmed": "false",
  "payment_setting.compliance_terms_version": "",
  "payment_setting.compliance_confirmed_at": "0",
  "payment_setting.compliance_confirmed_by": "0",
  "payment_setting.compliance_confirmed_ip": "",
  "perf_metrics_setting.enabled": "true",
  "perf_metrics_setting.flush_interval": "5",
  "perf_metrics_setting.bucket_time": "hour",
  "perf_metrics_setting.retention_days": "0",
  "performance_setting.disk_cache_enabled": "false",
  "performance_setting.disk_cache_threshold_mb": "10",
  "performance_setting.disk_cache_max_size_mb": "1024",
  "performance_setting.disk_cache_path": "",
  "performance_setting.monitor_enabled": "true",
  "performance_setting.monitor_cpu_threshold": "90",
  "performance_setting.monitor_memory_threshold": "90",
  "performance_setting.monitor_disk_threshold": "95",
  "fetch_setting.enable_ssrf_protection": "true",
  "fetch_setting.allow_private_ip": "false",
  "fetch_setting.domain_filter_mode": "false",
  "fetch_setting.ip_filter_mode": "false",
  "fetch_setting.domain_list": "[]",
  "fetch_setting.ip_list": "[]",
  "fetch_setting.allowed_ports": JSON.stringify(["80", "443", "8080", "8443"]),
  "fetch_setting.apply_ip_filter_for_domain": "true",
  "global.pass_through_request_enabled": "false",
  "global.thinking_model_blacklist": JSON.stringify(["moonshotai/kimi-k2-thinking", "kimi-k2-thinking"]),
  "global.effort_tail_model_ids": JSON.stringify([
    "gpt-5.1-codex-max",
    "qwen-image-edit-max",
    "qwen-max",
    "stable-diffusion-3-medium",
    "yi-medium",
  ]),
  "global.chat_completions_to_responses_policy": JSON.stringify({ enabled: false, all_channels: true }),
  "gemini.safety_settings": JSON.stringify({ default: "OFF" }),
  "gemini.version_settings": JSON.stringify({ default: "v1beta", "gemini-1.0-pro": "v1" }),
  "gemini.supported_imagine_models": JSON.stringify([
    "gemini-2.0-flash-exp-image-generation",
    "gemini-2.0-flash-exp",
    "gemini-3-pro-image-preview",
    "gemini-3-pro-image",
    "gemini-2.5-flash-image",
    "gemini-3.1-flash-image",
    "gemini-3.1-flash-image-preview",
  ]),
  "gemini.thinking_adapter_enabled": "false",
  "gemini.thinking_adapter_budget_tokens_percentage": "0.6",
  "gemini.function_call_thought_signature_enabled": "true",
  "gemini.remove_function_response_id_enabled": "true",
  "claude.model_headers_settings": "{}",
  "claude.default_max_tokens": JSON.stringify({ default: 8192 }),
  "claude.thinking_adapter_enabled": "true",
  "claude.thinking_adapter_budget_tokens_percentage": "0.8",
  "grok.violation_deduction_enabled": "true",
  "grok.violation_deduction_amount": "0.05",
  "qwen.sync_image_models": JSON.stringify([
    "z-image",
    "qwen-image",
    "wan2.6",
    "wan2.7",
    "qwen-image-edit",
    "qwen-image-edit-max",
    "qwen-image-edit-max-2026-01-16",
    "qwen-image-edit-plus",
    "qwen-image-edit-plus-2025-12-15",
    "qwen-image-edit-plus-2025-10-30",
  ]),
  "group_ratio_setting.group_ratio": JSON.stringify({ default: 1, vip: 1, svip: 1 }),
  "group_ratio_setting.group_group_ratio": JSON.stringify({ vip: { edit_this: 0.9 } }),
  "group_ratio_setting.group_special_usable_group": "{}",
  "billing_setting.billing_mode": "{}",
  "billing_setting.billing_expr": "{}",
  "tool_price_setting.prices": "{}",
  "task_pricing_setting.sora_size_ratio": JSON.stringify({ "1792x1024": 1.666667, "1024x1792": 1.666667 }),
  "task_pricing_setting.vertex_resolution_4k_ratio": JSON.stringify({
    "veo-3.1-fast-generate": 2.333333,
    "veo-3.1-generate": 1.5,
    "veo-3.1": 1.5,
  }),
  "channel_affinity_setting.enabled": "true",
  "channel_affinity_setting.switch_on_success": "true",
  "channel_affinity_setting.keep_on_channel_disabled": "false",
  "channel_affinity_setting.max_entries": "100000",
  "channel_affinity_setting.default_ttl_seconds": "3600",
  "channel_affinity_setting.rules": JSON.stringify(CHANNEL_AFFINITY_RULES),
};

/** Bidirectional aliases between original nested keys and legacy top-level keys. */
const ALIAS_PAIRS: [string, string][] = [
  ["CheckinEnabled", "checkin_setting.enabled"],
  ["CheckinMinQuota", "checkin_setting.min_quota"],
  ["CheckinMaxQuota", "checkin_setting.max_quota"],
  ["PasskeyEnabled", "passkey.enabled"],
  ["PasskeyDisplayName", "passkey.rp_display_name"],
  ["PasskeyRPID", "passkey.rp_id"],
  ["PasskeyOrigins", "passkey.origins"],
  ["PasskeyAllowInsecure", "passkey.allow_insecure_origin"],
  ["PasskeyUserVerification", "passkey.user_verification"],
  ["PasskeyAttachment", "passkey.attachment_preference"],
  ["UptimeKumaEnabled", "console_setting.uptime_kuma_enabled"],
  ["UptimeKumaGroups", "console_setting.uptime_kuma_groups"],
  ["ApiInfoEnabled", "console_setting.api_info_enabled"],
  ["AnnouncementsEnabled", "console_setting.announcements_enabled"],
  ["FAQEnabled", "console_setting.faq_enabled"],
  ["ApiInfo", "console_setting.api_info"],
  ["Announcements", "console_setting.announcements"],
  ["FAQ", "console_setting.faq"],
  ["OIDCAuthEnabled", "oidc.enabled"],
  ["OIDCClientId", "oidc.client_id"],
  ["OIDCClientSecret", "oidc.client_secret"],
  ["OIDCAuthorizationEndpoint", "oidc.authorization_endpoint"],
  ["OIDCTokenEndpoint", "oidc.token_endpoint"],
  ["OIDCUserinfoEndpoint", "oidc.user_info_endpoint"],
  ["OIDCDisplayName", "oidc.display_name"],
  ["DiscordOAuthEnabled", "discord.enabled"],
  ["DiscordClientId", "discord.client_id"],
  ["DiscordClientSecret", "discord.client_secret"],
  ["UserAgreement", "legal.user_agreement"],
  ["PrivacyPolicy", "legal.privacy_policy"],
  ["DocsLink", "general_setting.docs_link"],
  ["QuotaDisplayType", "general_setting.quota_display_type"],
  ["CustomCurrencySymbol", "general_setting.custom_currency_symbol"],
  ["CustomCurrencyExchangeRate", "general_setting.custom_currency_exchange_rate"],
  ["AmountOptions", "payment_setting.amount_options"],
  ["AmountDiscount", "payment_setting.amount_discount"],
  ["PaymentComplianceConfirmed", "payment_setting.compliance_confirmed"],
  ["PaymentComplianceTermsVersion", "payment_setting.compliance_terms_version"],
  ["DisplayInCurrency", "DisplayInCurrencyEnabled"],
  ["EpayPid", "EpayId"],
  ["MinTopup", "MinTopUp"],
];

export const OPTION_ALIASES: Record<string, string[]> = {};
for (const [a, b] of ALIAS_PAIRS) {
  (OPTION_ALIASES[a] ||= []).push(b);
  (OPTION_ALIASES[b] ||= []).push(a);
}

export const DEFAULT_MARKETPLACE_SOURCES = [
  { name: "Official", index_url: "https://www.newapi.ai/api/v1/plugins/index.json" },
  { name: "GitHub", index_url: "https://raw.githubusercontent.com/QuantumNous/new-api-plugins/main/index.json" },
];
